name: Check
"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
      - name: Lint
        run: deno lint
      - name: Check
        run: deno task check
      - name: Test
        run: deno test
